#!/usr/bin/env python3
"""
Save Stage 1 outputs as RAW binary files + ImageJ macro for direct import.

Why RAW?
--------
ImageJ's  File > Import > Raw...  reads any flat binary array directly —
no library needed on the Python side, no plugin needed on the ImageJ side.
The accompanying .ijm macro encodes every dimension so import is one click.

Files produced (in --out-dir)
------------------------------
    raw/clean_proj_180x96x128_float32.raw   projection stack, clean
    raw/noisy_proj_180x96x128_float32.raw   projection stack, noisy
    raw/phantom_64x128x128_float32.raw      attenuation volume

    macros/open_clean_proj.ijm   drag-and-drop into ImageJ to open
    macros/open_noisy_proj.ijm
    macros/open_phantom.ijm
    macros/open_all.ijm          opens all three at once

Data layout
-----------
All files are:
    • Little-endian float32  (4 bytes per voxel)
    • C-order (last index fastest): frame × row × col
    • No header bytes

In ImageJ Raw import dialog:
    Image type  : 32-bit Real
    Byte order  : Little-endian
    Width/Height/Number: from filename or macro

Usage
-----
    python save_as_raw.py                       # reads from results/
    python save_as_raw.py --out-dir my_results  # custom folder
    python save_as_raw.py --no-volume           # skip large phantom file
"""

import argparse
import json
import struct
from pathlib import Path

import numpy as np


# ---------------------------------------------------------------------------
# RAW writer
# ---------------------------------------------------------------------------

def save_raw(arr: np.ndarray, path: Path) -> int:
    """
    Write array as little-endian float32 RAW binary.

    Returns file size in bytes.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    data = arr.astype("<f4")          # little-endian float32
    path.write_bytes(data.tobytes())
    return path.stat().st_size


# ---------------------------------------------------------------------------
# ImageJ macro generator
# ---------------------------------------------------------------------------

def _ijm(title: str, raw_path: Path, shape: tuple,
          macro_path: Path) -> None:
    """
    Write an ImageJ macro (.ijm) that imports the RAW file with one run.

    shape is (n_frames, height, width)  i.e. (Z, Y, X).
    """
    n_frames, height, width = shape
    # Make path relative to macro location for portability
    # Use absolute path as fallback
    abs_raw = raw_path.resolve().as_posix()
    rel_raw = raw_path.name   # just the filename (macro lives next to raw/)

    macro = f"""\
// ─────────────────────────────────────────────────────────────────
// ImageJ macro — auto-generated by save_as_raw.py
// Opens: {raw_path.name}
//
// How to use:
//   Drag this .ijm file onto ImageJ  OR
//   Plugins > Macros > Run...  →  select this file
//
// Data: little-endian float32, no header
//       {width} cols × {height} rows × {n_frames} frames
// ─────────────────────────────────────────────────────────────────

// --- locate RAW file next to this macro ---
var macroDir = getDirectory("macros");
var rawFile  = macroDir + "../raw/" + "{raw_path.name}";

// Fallback: absolute path written at generation time
if (!File.exists(rawFile)) {{
    rawFile = "{abs_raw}";
}}

if (!File.exists(rawFile)) {{
    exit("Cannot find RAW file:\\n" + rawFile +
         "\\n\\nMove the raw/ folder next to the macros/ folder, or edit this macro.");
}}

// --- import ---
run("Raw...",
    "open=" + rawFile +
    " image=[32-bit Real]" +
    " width={width}" +
    " height={height}" +
    " number={n_frames}" +
    " little-endian");

rename("{title}");
resetMinAndMax();

// --- enhance display ---
run("Enhance Contrast", "saturated=0.35");
run("Grays");

// --- for projection stacks: show as a scrollable stack ---
if ({n_frames} > 1) {{
    Stack.setDimensions(1, 1, {n_frames});  // channels=1, slices=1, frames=n
    setSlice(1);
    print("\\nOpened: {title}");
    print("  Dimensions : {width} x {height} x {n_frames} frames");
    print("  Scroll the slider or press \\\\ to animate.");
}}
"""
    macro_path.parent.mkdir(parents=True, exist_ok=True)
    macro_path.write_text(macro)


def _ijm_all(entries: list[tuple], macro_path: Path) -> None:
    """
    Write a single macro that opens all RAW files.

    entries: list of (title, raw_path, shape)
    """
    lines = [
        "// open_all.ijm — opens all Stage 1 RAW outputs",
        "// Drag onto ImageJ or run via Plugins > Macros > Run...",
        "",
    ]
    for title, raw_path, shape in entries:
        n, h, w = shape
        abs_raw = raw_path.resolve().as_posix()
        lines += [
            f'// --- {title} ---',
            f'rawFile = "{abs_raw}";',
            f'run("Raw...", "open=" + rawFile + " image=[32-bit Real]"'
            f' + " width={w} height={h} number={n} little-endian");',
            f'rename("{title}");',
            f'resetMinAndMax();',
            f'run("Enhance Contrast", "saturated=0.35");',
            f'run("Grays");',
            "",
        ]
    macro_path.write_text("\n".join(lines))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(
        description="Save Stage 1 .npy files as RAW + ImageJ macros",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--out-dir",   default="results",
                   help="Stage 1 results directory  (default: results)")
    p.add_argument("--no-volume", action="store_true",
                   help="Skip phantom volume (saves time/disk)")
    args = p.parse_args()

    out       = Path(args.out_dir)
    raw_dir   = out / "raw"
    macro_dir = out / "macros"
    raw_dir.mkdir(parents=True, exist_ok=True)
    macro_dir.mkdir(parents=True, exist_ok=True)

    # ── Discover files ────────────────────────────────────────────────────────
    targets = [
        (out / "projections" / "clean.npy", "clean_projections"),
        (out / "projections" / "noisy.npy", "noisy_projections"),
    ]
    if not args.no_volume:
        targets.append((out / "volume" / "phantom.npy", "phantom_volume"))

    print("=" * 62)
    print("  Stage 1 → RAW + ImageJ macro exporter")
    print("=" * 62)

    all_entries = []

    for npy_path, label in targets:
        if not npy_path.exists():
            print(f"\n  ⚠  Skipping (not found): {npy_path}")
            continue

        print(f"\n  [{label}]")
        print(f"    Loading  {npy_path} …")
        arr = np.load(npy_path).astype(np.float32)

        # Ensure 3-D
        if arr.ndim == 2:
            arr = arr[np.newaxis]

        n_frames, height, width = arr.shape
        print(f"    Shape    : {n_frames} × {height} × {width}  "
              f"(frames × rows × cols)")
        print(f"    Range    : [{arr.min():.4f},  {arr.max():.4f}]")

        # RAW filename encodes shape and dtype for clarity
        raw_name = f"{label}_{n_frames}x{height}x{width}_float32.raw"
        raw_path = raw_dir / raw_name

        nbytes = save_raw(arr, raw_path)
        print(f"    RAW      → {raw_path.name}  ({nbytes/1e6:.1f} MB)")

        # Per-file macro
        macro_path = macro_dir / f"open_{label}.ijm"
        _ijm(label, raw_path, (n_frames, height, width), macro_path)
        print(f"    Macro    → {macro_path.name}")

        all_entries.append((label, raw_path, (n_frames, height, width)))

    # Combined macro
    if all_entries:
        all_macro = macro_dir / "open_all.ijm"
        _ijm_all(all_entries, all_macro)
        print(f"\n  Combined macro → {all_macro}")

    # Write a plain-text README next to the raw files
    readme = raw_dir / "README_ImageJ.txt"
    readme.write_text(
        "How to open these RAW files in ImageJ\n"
        "======================================\n\n"
        "Option A — Use the macro (easiest)\n"
        "  1. Open ImageJ / Fiji\n"
        "  2. Drag  ../macros/open_<name>.ijm  onto the ImageJ toolbar\n"
        "     OR  Plugins > Macros > Run...  → select the .ijm file\n"
        "  The image opens automatically with correct dimensions.\n\n"
        "Option B — Manual import\n"
        "  1. File > Import > Raw...\n"
        "  2. Select the .raw file\n"
        "  3. Fill in the dialog:\n"
        "       Image type  :  32-bit Real\n"
        "       Width       :  <last number in filename, e.g. 128>\n"
        "       Height      :  <middle number,           e.g. 96>\n"
        "       Number      :  <first number,            e.g. 180>\n"
        "       Byte order  :  Little-endian\n"
        "       Header size :  0\n"
        "  4. Press OK.\n\n"
        "Useful ImageJ commands after opening\n"
        "  Ctrl+Shift+C          Brightness/Contrast auto-scale\n"
        "  \\  (backslash)        Animate the stack\n"
        "  Image > Stacks > Z Project > Max Intensity\n"
        "  Analyze > Plot Profile   (draw a line first with the line tool)\n"
        "  Plugins > 3D Viewer      (volume render the phantom stack)\n"
    )
    print(f"\n  README      → {readme}")

    print(f"\n{'='*62}")
    print(f"  Done — {len(all_entries)} file(s) exported.")
    print(f"\n  Quick open in ImageJ:")
    print(f"    Drag  {macro_dir}/open_all.ijm  onto ImageJ toolbar")
    print()


if __name__ == "__main__":
    main()
